### ISSUE TITLE
Initial push fails if `git config push.default current` is not set

### ISSUE THREAD

**Issue by pichfl** [anfema/work#16]
```sh
⠹ Creating developError creating branch { Error: Command failed: git push --set-upstream
fatal: The current branch s.tenpas/730-brands-overview-page-is-rendered-twice has no upstream branch.
To push the current branch and set the remote as upstream, use

   git push --set-upstream origin s.tenpas/730-brands-overview-page-is-rendered-twice



   at makeError (/Users/sven/.config/yarn/global/node_modules/work/node_modules/execa/index.js:174:9)
   at Promise.all.then.arr (/Users/sven/.config/yarn/global/node_modules/work/node_modules/execa/index.js:278:16)
   at process._tickCallback (internal/process/next_tick.js:68:7)
 code: 128,
 stdout: ‘’,
 stderr:
  ‘fatal: The current branch s.tenpas/730-brands-overview-page-is-rendered-twice has no upstream branch.\nTo push the current branch and set the remote as upstream, use\n\n    git push --set-upstream origin s.tenpas/730-brands-overview-page-is-rendered-twice\n\n’,
 failed: true,
 signal: null,
 cmd: ‘git push --set-upstream’,
 timedOut: false,
 killed: false }
⠸ Synching to GitHub
```

via @zehnnach

To resolve this that setting should be checked and if not set, the upstream should be set manually.

**Comment by p-fischer** [comment]
I think the cleaner solution is not to rely on the `push.default` setting, but to change the command as suggested in the error message, i.e. replace
```
git push --set-upstream
```
with
```
git push --set-upstream origin s.tenpas/730-brands-overview-page-is-rendered-twice
```
