### ISSUE TITLE
ticketlist via wizard is not working

### ISSUE THREAD

**Issue by Somberland** [anfema/work#74]
> work
> ? What do you want to do? Create a branch for an issue (From the current active branch!)
> ? Which issue should be worked on? Leave empty to select from open (Please Note: The new branch will be based on the currently active branch!) 

```
HttpError: Invalid value for parameter 'number': "" is NaN
    at /Users/philippskorpil/.config/yarn/global/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:89:17
    at Array.forEach (<anonymous>)
    at /Users/philippskorpil/.config/yarn/global/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:54:12
    at Array.forEach (<anonymous>)
    at validate (/Users/philippskorpil/.config/yarn/global/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:32:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/Users/philippskorpil/.config/yarn/global/node_modules/work/src/create-branch.js:43:15)
    at async /Users/philippskorpil/.config/yarn/global/node_modules/work/index.js:22:5 {
  code: 400,
  status: 'Bad Request',
  headers: undefined
}
✖ Unable to build branch name
```

reported by @p-fischer

**Comment by p-fischer** [comment]
It still works on my old computer.
Both my old and new computer have work v1.4.2 installed

The command `work -i` works on both computers.

**Comment by p-fischer** [comment]
Now, I can't create any branch with work anymore because neither showing the list via
```
work -i
```
nor directly creating an issue via  
```
work -i 123
```
works anymore.


The output of `work -i`:
```
(node:80410) [DEP0170] DeprecationWarning: The URL http://git@github.com:anfema/hairhaus-mde.git is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)

Hello p.fischer
You're working on anfema/hairhaus-mde!

[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
Error requesting GitHub issues for anfema/hairhaus-mde TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
? Which issue do you want to work on? (Use arrow keys)

/Users/peterfischer/.config/yarn/global/node_modules/inquirer/lib/prompts/list.js:148
    return this.opt.choices.getChoice(this.selected).value;
                                                    ^

TypeError: Cannot read properties of undefined (reading 'value')
    at ListPrompt.getCurrentValue (/Users/peterfischer/.config/yarn/global/node_modules/inquirer/lib/prompts/list.js:148:53)
    at MapSubscriber._next (/Users/peterfischer/.config/yarn/global/node_modules/rxjs/internal/operators/map.js:49:35)
    at Subscriber.next (/Users/peterfischer/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/Users/peterfischer/.config/yarn/global/node_modules/rxjs/internal/operators/take.js:54:30)
    at Subscriber.next (/Users/peterfischer/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (/Users/peterfischer/.config/yarn/global/node_modules/rxjs/internal/observable/fromEvent.js:22:28)
    at Interface.emit (node:events:526:35)
    at [_onLine] [as _onLine] (node:internal/readline/interface:416:12)
    at [_line] [as _line] (node:internal/readline/interface:887:18)
    at [_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1265:22)

Node.js v20.5.0
```


Output of `work -i 807`:
```
(node:80477) [DEP0170] DeprecationWarning: The URL http://git@github.com:anfema/hairhaus-mde.git is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)

Hello p.fischer
You're working on anfema/hairhaus-mde!

⠇ Checking git status[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest/node_modules/macos-release/index.js:28:26)
    at osName (/Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest/node_modules/os-name/index.js:21:18)
    at getUserAgentNode (/Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest/node_modules/universal-user-agent/index.js:7:53)
    at restEndpoint (/Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest/lib/endpoint/index.js:27:48)
    at restRequest (/Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest/lib/request/index.js:7:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/Users/peterfischer/.config/yarn/global/node_modules/work/src/create-branch.js:43:15)
    at async /Users/peterfischer/.config/yarn/global/node_modules/work/index.js:22:5
✖ Unable to build branch name
```

**Comment by Somberland** [comment]
@p-fischer hotfix:
  just update the `/Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest/node_modules/macos-release/index.js'  and add sonoma there :)

**Comment by p-fischer** [comment]
> /Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest/

I can't find the `node_modules` folder under `/Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest` 🤔 

``` 
❯ cd /Users/peterfischer/.config/yarn/global/node_modules/@octokit/rest 

 ~/.config/yarn/global/node_modules/@octokit/rest ❯ ls       
LICENSE       README.md     index.d.ts    index.js      index.js.flow lib           package.json
```
